name: Docker Image CI

on:
  push:
    tags: ["v*"]
  pull_request:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract image tag
        run: |
          RAW_VERSION="$(git describe --tags --abbrev=0)"
          CLEAN_VERSION="${RAW_VERSION#v}"
          echo "IMAGE_TAG=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "Using Docker image tag: $CLEAN_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/wujihandcpp-develop:${{ env.IMAGE_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/wujihandcpp-develop:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
