name: Release Package CI

permissions:
  contents: write

on:
  push:
    tags: ["v*"]
  pull_request:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build release package (${{ matrix.arch }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.package-builder
          outputs: type=local,dest=package-build/
          cache-from: type=gha,scope=release-build-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=release-build-${{ matrix.arch }}

      - name: List built packages
        run: find package-build/*

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.arch }}
          path: |
            package-build/*.deb
            package-build/*.rpm
            package-build/*.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Extract git tag & generate change log
        run: |
          GIT_TAG="$(git describe --tags --abbrev=0)"
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "Using git tag: $GIT_TAG"
          docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog $GIT_TAG > changelog.md
          cat changelog.md

      - name: Download all built packages
        uses: actions/download-artifact@v4
        with:
          path: package-build/
          pattern: package-*
          merge-multiple: true

      - name: List built packages
        run: find package-build/*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          name: ${{ env.GIT_TAG }}
          body_path: changelog.md
          draft: false
          prerelease: ${{ github.ref_type != 'tag' }}
          make_latest: ${{ github.ref_type == 'tag' }}
          files: |
            package-build/*.deb
            package-build/*.rpm
            package-build/*.zip
