name: Release Package CI

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t packager:latest -f Dockerfile.packager .
      
    - name: Run package builder
      run: |
        docker run --rm \
          -v "$(pwd):/source:ro" \
          -v "$(pwd)/package-build:/output:rw" \
          packager:latest
          
    - name: List built packages
      run: ls -al package-build/
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: package-build/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
